#!/bin/bash

## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Perform various operations for ArchLan

fix_apps() {
	adir="/usr/share/applications"
	apps=(avahi-discover.desktop bssh.desktop bvnc.desktop echomixer.desktop \
	envy24control.desktop exo-preferred-applications.desktop feh.desktop \
	hdajackretask.desktop hdspconf.desktop hdspmixer.desktop hwmixvolume.desktop lftp.desktop \
	libfm-pref-apps.desktop lxshortcut.desktop lstopo.desktop \
	networkmanager_dmenu.desktop nm-connection-editor.desktop pcmanfm-desktop-pref.desktop \
	qv4l2.desktop qvidcap.desktop stoken-gui.desktop stoken-gui-small.desktop thunar-bulk-rename.desktop \
	thunar-settings.desktop thunar-volman-settings.desktop yad-icon-browser.desktop)

	for app in "${apps[@]}"; do
		if [[ -e "$adir/$app" ]]; then
			sed -i '$s/$/\nNoDisplay=true/' "$adir/$app"
		fi
	done
}

fix_pixmaps() {
	## Remove Arch Linux artworks
	imgs=('archlinux.png' 'archlinux.svg' 'archlinux-logo.png' 'archlinux-logo.svg')
	
	for img in "${imgs[@]}"; do
		if [[ -e /usr/share/pixmaps/"$img" ]]; then 
			rm -rf /usr/share/pixmaps/"$img"
		fi
	done	
}

fix_thunar() {
	## Remove thunar wallpaper plugin
	twplug='/usr/lib/thunarx-3/thunar-wallpaper-plugin.so'
	if [[ -e "$twplug" ]]; then
		rm -rf "$twplug"
	fi
}

fix_grub() {
	## Fix GRUB_DISTRIBUTOR for ArchLan
	sed -i -e 's/GRUB_DISTRIBUTOR=.*/GRUB_DISTRIBUTOR="ArchLan"/g' /etc/default/grub
	cat /etc/grub.d/10_linux | grep 'OS="${GRUB_DISTRIBUTOR} Linux"' &>/dev/null
	if [[ "$?" == 0 ]]; then
		sed -i -e 's/OS="${GRUB_DISTRIBUTOR} Linux"/OS="${GRUB_DISTRIBUTOR}"/g' /etc/grub.d/10_linux
	fi
}

main()
{
    local hookname="$1"

    case "$hookname" in
		fix-apps)	  fix_apps ;;
        fix-pixmaps)  fix_pixmaps ;;
        fix-thunar)   fix_thunar ;;
        fix-nmd)      fix_nmd ;;
        fix-grub)     fix_grub ;;
        "")           echo "Nothing to do!";;
    esac
}

main "$@"
